

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0742b4e673072066f
      InstanceType: t2.micro
      AvailabilityZone: us-east-1a
Outputs:
  MyEC2Instance1:
    Description: EC2 instance
    Value: !Ref MyEC2Instance
    Export:
      Name: MyEC2Instance1      