version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-hello"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q8s4n0n2ouw6"
s3_prefix = "sam-app-hello"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
